services:
  - type: web
    name: dastyar-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENAI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: LISTENNOTES_API_KEY
        sync: false
      - key: API_KEYS
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: API_RATE_LIMIT
        value: 200

  - type: redis
    name: dastyar-redis
    ipAllowList: []
    plan: free